<%@ Page Title="Settings" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="false" CodeBehind="Categories.aspx.vb" Inherits="ITSupportAssetManagement.Web.CategorySettingsPage" %>
<asp:Content ID="SettingsContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="page-heading ticket-page-heading"><div><p class="eyebrow">Administration</p><h1>Platform settings</h1><p>Control the categories available across tickets and asset inventory.</p></div></div>
    <asp:Panel ID="SuccessPanel" runat="server" CssClass="page-alert success" Visible="false"><i class="bi bi-check-circle"></i><asp:Literal ID="SuccessMessage" runat="server" /></asp:Panel>
    <asp:Panel ID="ErrorPanel" runat="server" CssClass="page-alert error" Visible="false"><i class="bi bi-exclamation-circle"></i><asp:Literal ID="ErrorMessage" runat="server" /></asp:Panel>
    <div class="settings-grid">
        <section class="panel category-panel"><div class="panel-heading"><div><h2>Ticket categories</h2><p>Classify support requests consistently</p></div><span class="settings-icon blue"><i class="bi bi-inbox"></i></span></div><div class="category-list"><asp:Repeater ID="TicketRepeater" runat="server"><ItemTemplate><article><div><strong><%#: Eval("Name") %></strong><small><%#: Eval("StatusText") %></small></div><asp:LinkButton ID="ToggleTicketButton" runat="server" CommandName="Toggle" CommandArgument='<%# Eval("Id") %>' CssClass='<%# If(Convert.ToBoolean(Eval("IsActive")), "mini-toggle active", "mini-toggle") %>' CausesValidation="false"><%# If(Convert.ToBoolean(Eval("IsActive")), "Deactivate", "Activate") %></asp:LinkButton></article></ItemTemplate></asp:Repeater></div><div class="category-composer"><asp:TextBox ID="TicketNameInput" runat="server" MaxLength="80" placeholder="New ticket category" /><asp:Button ID="AddTicketButton" runat="server" Text="Add category" CssClass="button button-primary" CausesValidation="false" /></div></section>
        <section class="panel category-panel"><div class="panel-heading"><div><h2>Asset categories</h2><p>Organize the equipment inventory</p></div><span class="settings-icon green"><i class="bi bi-laptop"></i></span></div><div class="category-list"><asp:Repeater ID="AssetRepeater" runat="server"><ItemTemplate><article><div><strong><%#: Eval("Name") %></strong><small><%#: Eval("StatusText") %></small></div><asp:LinkButton ID="ToggleAssetButton" runat="server" CommandName="Toggle" CommandArgument='<%# Eval("Id") %>' CssClass='<%# If(Convert.ToBoolean(Eval("IsActive")), "mini-toggle active", "mini-toggle") %>' CausesValidation="false"><%# If(Convert.ToBoolean(Eval("IsActive")), "Deactivate", "Activate") %></asp:LinkButton></article></ItemTemplate></asp:Repeater></div><div class="category-composer"><asp:TextBox ID="AssetNameInput" runat="server" MaxLength="80" placeholder="New asset category" /><asp:Button ID="AddAssetButton" runat="server" Text="Add category" CssClass="button button-primary" CausesValidation="false" /></div></section>
    </div>
</asp:Content>
