SET XACT_ABORT ON;
BEGIN TRANSACTION;

UPDATE dbo.Tickets
SET DueAtUtc = DATEADD(HOUR, CASE Priority WHEN N'Critical' THEN 4 WHEN N'High' THEN 8 WHEN N'Medium' THEN 24 ELSE 72 END, CreatedAtUtc)
WHERE DueAtUtc IS NULL;

COMMIT TRANSACTION;
