<%@ Page Title="Overview" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="false" CodeBehind="Default.aspx.vb" Inherits="ITSupportAssetManagement.Web.HomePage" %>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <section class="dashboard-hero">
        <div class="hero-copy"><p class="hero-kicker"><span></span> Operations command center</p><h1><asp:Literal ID="GreetingText" runat="server" /></h1><p>Monitor requests, equipment, and technical interventions across the Siliana site.</p><div class="hero-meta"><span><i class="bi bi-geo-alt"></i> Siliana plant</span><span><i class="bi bi-calendar3"></i> <asp:Literal ID="CurrentDateText" runat="server" /></span><span><i class="bi bi-clock"></i> <asp:Literal ID="ShiftText" runat="server" /></span></div></div>
        <div class="hero-side"><div class="live-status"><span class="live-dot"></span><div><small>Platform status</small><strong>All systems operational</strong></div></div><div class="heading-actions"><button class="button hero-secondary" type="button"><i class="bi bi-download"></i> Export report</button><a class="button hero-primary" href="Tickets/Create.aspx"><i class="bi bi-plus-lg"></i> New ticket</a></div></div>
    </section>
    <section class="metric-grid dashboard-metrics" aria-label="Key metrics">
        <article class="metric-card metric-blue"><div class="metric-top"><span class="metric-icon"><i class="bi bi-inbox"></i></span><span class="live-data-label">Live</span></div><p>Open tickets</p><div class="metric-value"><asp:Literal ID="OpenTicketsText" runat="server" /></div><small><asp:Literal ID="AttentionTicketsText" runat="server" /> require attention</small></article>
        <article class="metric-card metric-violet"><div class="metric-top"><span class="metric-icon"><i class="bi bi-laptop"></i></span><span class="live-data-label">Live</span></div><p>Total assets</p><div class="metric-value"><asp:Literal ID="TotalAssetsText" runat="server" /></div><small><asp:Literal ID="AssignedAssetsText" runat="server" /> currently assigned</small></article>
        <article class="metric-card metric-orange"><div class="metric-top"><span class="metric-icon"><i class="bi bi-tools"></i></span><span class="live-data-label">Live</span></div><p>In maintenance</p><div class="metric-value"><asp:Literal ID="MaintenanceAssetsText" runat="server" /></div><small><asp:Literal ID="OverdueMaintenanceText" runat="server" /> overdue interventions</small></article>
        <article class="metric-card metric-green"><div class="metric-top"><span class="metric-icon"><i class="bi bi-stopwatch"></i></span><span class="live-data-label">30-day view</span></div><p>Avg. resolution</p><div class="metric-value"><asp:Literal ID="AverageResolutionText" runat="server" />h</div><small>Target is under 4 hours</small></article>
    </section>
    <div class="dashboard-grid">
        <section class="panel ticket-panel" id="tickets">
            <div class="panel-heading"><div><h2>Priority tickets</h2><p>Requests that need your team&rsquo;s attention</p></div><a href="#all-tickets">View all <i class="bi bi-arrow-right"></i></a></div>
            <div class="ticket-list"><asp:Repeater ID="PriorityTicketRepeater" runat="server"><ItemTemplate><a class="ticket-row" href='<%# "Tickets/Details.aspx?id=" & Convert.ToString(Eval("TicketId")) %>'><span class='<%# "priority priority-" & Convert.ToString(Eval("PriorityCss")) %>'></span><div class="ticket-main"><div><span class="ticket-id"><%#: Eval("TicketNumber") %></span><span class='<%# "status status-" & Convert.ToString(Eval("PriorityCss")) %>'><%#: Eval("Priority") %></span></div><h3><%#: Eval("Title") %></h3><p><i class="bi bi-building"></i> <%#: Eval("CategoryName") %> &middot; <%#: FormatAge(Eval("CreatedAtUtc")) %></p></div><div class="assignee"><span class="avatar avatar-indigo"><%#: Eval("Initials") %></span><span><strong><%#: DisplayAssignee(Eval("AssignedToName")) %></strong><small>Assigned technician</small></span></div><span class="more-button"><i class="bi bi-arrow-right"></i></span></a></ItemTemplate></asp:Repeater><asp:Panel ID="NoPriorityTicketsPanel" runat="server" CssClass="dashboard-empty" Visible="false"><i class="bi bi-check2-circle"></i><strong>No active tickets</strong><span>Your support queue is clear.</span></asp:Panel></div>
        </section>
        <section class="panel health-panel" id="assets">
            <div class="panel-heading"><div><h2>Asset health</h2><p>Current fleet condition</p></div><button class="more-button" type="button" aria-label="Asset options"><i class="bi bi-three-dots"></i></button></div>
            <div class="health-chart"><div id="HealthRing" runat="server" class="health-ring"><div><strong><asp:Literal ID="HealthyPercentageText" runat="server" />%</strong><span>Healthy</span></div></div></div>
            <div class="health-legend"><div><span class="legend-dot healthy"></span><p><strong><asp:Literal ID="HealthyAssetsText" runat="server" /></strong> Healthy</p><em><asp:Literal ID="HealthyLegendPercentage" runat="server" />%</em></div><div><span class="legend-dot warning"></span><p><strong><asp:Literal ID="AttentionAssetsText" runat="server" /></strong> Needs attention</p><em><asp:Literal ID="AttentionLegendPercentage" runat="server" />%</em></div><div><span class="legend-dot danger"></span><p><strong><asp:Literal ID="MaintenanceLegendCount" runat="server" /></strong> In maintenance</p><em><asp:Literal ID="MaintenanceLegendPercentage" runat="server" />%</em></div></div>
            <button class="button button-quiet" type="button">Open asset inventory <i class="bi bi-arrow-right"></i></button>
        </section>
    </div>
    <div class="dashboard-grid lower-grid">
        <section class="panel activity-panel" id="maintenance">
            <div class="panel-heading"><div><h2>Recent activity</h2><p>Latest updates from your IT team</p></div><select aria-label="Activity period"><option>Today</option><option>This week</option></select></div>
            <div class="timeline"><asp:Repeater ID="ActivityRepeater" runat="server"><ItemTemplate><div class="timeline-item"><span class='<%# "timeline-icon " & Convert.ToString(Eval("ColorClass")) %>'><i class='<%# Eval("IconClass") %>'></i></span><div><p><strong><%#: Eval("Title") %></strong></p><small><%#: Eval("Detail") %> &middot; <%#: FormatAge(Eval("EventAtUtc")) %></small></div></div></ItemTemplate></asp:Repeater><asp:Panel ID="NoActivityPanel" runat="server" CssClass="activity-empty" Visible="false"><i class="bi bi-activity"></i><span>Activity will appear as your team uses the platform.</span></asp:Panel></div>
        </section>
        <section class="panel quick-panel">
            <div class="panel-heading"><div><h2>Quick actions</h2><p>Common IT workflows</p></div></div>
            <div class="quick-grid"><a href="Tickets/Create.aspx"><span class="quick-icon blue"><i class="bi bi-plus-circle"></i></span><span><strong>Create ticket</strong><small>Log a new request</small></span><i class="bi bi-chevron-right"></i></a><a href="Assets/Create.aspx"><span class="quick-icon violet"><i class="bi bi-upc-scan"></i></span><span><strong>Add asset</strong><small>Register equipment</small></span><i class="bi bi-chevron-right"></i></a><a href="Maintenance/Create.aspx"><span class="quick-icon orange"><i class="bi bi-calendar2-check"></i></span><span><strong>Plan maintenance</strong><small>Schedule intervention</small></span><i class="bi bi-chevron-right"></i></a><a href="Tickets/List.aspx"><span class="quick-icon green"><i class="bi bi-list-check"></i></span><span><strong>Support queue</strong><small>Review open requests</small></span><i class="bi bi-chevron-right"></i></a></div>
        </section>
    </div>
</asp:Content>
