<%@ Page Title="Create administrator" Language="VB" AutoEventWireup="false" CodeBehind="SetupAdmin.aspx.vb" Inherits="ITSupportAssetManagement.Web.SetupAdminPage" %>
<!DOCTYPE html>
<html lang="en"><head runat="server"><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title>Initial setup - Siliana IT Hub</title><link rel="preconnect" href="https://fonts.googleapis.com" /><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous" /><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&amp;family=Manrope:wght@700;800&amp;display=swap" rel="stylesheet" /><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet" /><link href="Content/auth.css?v=20260831.2" rel="stylesheet" /></head>
<body><form id="SetupForm" runat="server" class="setup-shell"><section class="setup-card"><div class="setup-icon"><i class="bi bi-shield-lock"></i></div><p class="eyebrow">One-time setup</p><h1>Create the administrator</h1><p class="auth-intro">This page closes automatically after the first account is created.</p>
    <asp:Panel ID="ErrorPanel" runat="server" CssClass="auth-alert" Visible="false"><i class="bi bi-exclamation-circle"></i><asp:Literal ID="ErrorMessage" runat="server" /></asp:Panel>
    <div class="field-grid"><div class="field"><label for="FirstNameInput">First name</label><asp:TextBox ID="FirstNameInput" runat="server" MaxLength="80" autocomplete="given-name" /><asp:RequiredFieldValidator ID="FirstNameRequired" runat="server" ControlToValidate="FirstNameInput" ErrorMessage="Required." CssClass="field-error" Display="Dynamic" /></div><div class="field"><label for="LastNameInput">Last name</label><asp:TextBox ID="LastNameInput" runat="server" MaxLength="80" autocomplete="family-name" /><asp:RequiredFieldValidator ID="LastNameRequired" runat="server" ControlToValidate="LastNameInput" ErrorMessage="Required." CssClass="field-error" Display="Dynamic" /></div></div>
    <div class="field"><label for="EmailInput">Email address</label><asp:TextBox ID="EmailInput" runat="server" TextMode="Email" MaxLength="254" autocomplete="email" /><asp:RequiredFieldValidator ID="EmailRequired" runat="server" ControlToValidate="EmailInput" ErrorMessage="Email is required." CssClass="field-error" Display="Dynamic" /></div>
    <div class="field"><label for="PasswordInput">Password</label><asp:TextBox ID="PasswordInput" runat="server" TextMode="Password" MaxLength="128" autocomplete="new-password" /><asp:RequiredFieldValidator ID="PasswordRequired" runat="server" ControlToValidate="PasswordInput" ErrorMessage="Password is required." CssClass="field-error" Display="Dynamic" /><small>Use at least 12 characters with uppercase, lowercase, number, and symbol.</small></div>
    <div class="field"><label for="ConfirmPasswordInput">Confirm password</label><asp:TextBox ID="ConfirmPasswordInput" runat="server" TextMode="Password" MaxLength="128" autocomplete="new-password" /><asp:CompareValidator ID="PasswordMatch" runat="server" ControlToValidate="ConfirmPasswordInput" ControlToCompare="PasswordInput" ErrorMessage="Passwords do not match." CssClass="field-error" Display="Dynamic" /></div>
    <asp:Button ID="CreateButton" runat="server" Text="Create administrator" CssClass="auth-button" /><p class="auth-footnote"><i class="bi bi-database-check"></i> Your password is hashed before it reaches the database.</p>
</section></form></body></html>
