<%@ Page Title="Ticket details" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="false" CodeBehind="Details.aspx.vb" Inherits="ITSupportAssetManagement.Web.TicketDetailsPage" %>
<asp:Content ID="TicketDetailsContent" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Panel ID="NotFoundPanel" runat="server" CssClass="panel empty-state" Visible="false"><span><i class="bi bi-search"></i></span><h2>Ticket not found</h2><p>The requested ticket does not exist or is no longer available.</p><a class="button button-primary" href="List.aspx">Return to tickets</a></asp:Panel>
    <asp:Panel ID="DetailsPanel" runat="server" Visible="false">
        <div class="page-heading ticket-page-heading"><div><a class="back-link" href="List.aspx"><i class="bi bi-arrow-left"></i> Back to tickets</a><div class="details-title-row"><h1><asp:Literal ID="TicketTitle" runat="server" /></h1><asp:Label ID="PriorityBadge" runat="server" /></div><p><asp:Literal ID="TicketNumber" runat="server" /> &middot; Created <asp:Literal ID="CreatedDate" runat="server" /></p></div></div>
        <asp:Panel ID="SuccessPanel" runat="server" CssClass="page-alert success" Visible="false"><i class="bi bi-check-circle"></i>The ticket was updated successfully.</asp:Panel><asp:Panel ID="ErrorPanel" runat="server" CssClass="page-alert error" Visible="false"><i class="bi bi-exclamation-circle"></i><asp:Literal ID="ErrorMessage" runat="server" /></asp:Panel>
        <div class="ticket-details-grid"><div class="ticket-detail-stack"><section class="panel details-main"><div class="panel-heading"><div><h2>Issue description</h2><p>Information provided by the requester</p></div></div><div class="description-copy"><asp:Literal ID="DescriptionText" runat="server" /></div></section><section class="panel conversation-panel"><div class="panel-heading"><div><h2>Conversation</h2><p>Updates shared throughout the ticket lifecycle</p></div></div><div class="comment-list"><asp:Repeater ID="CommentRepeater" runat="server"><ItemTemplate><article class='<%# If(Convert.ToBoolean(Eval("IsInternal")), "ticket-comment internal", "ticket-comment") %>'><span class="avatar"><%#: Eval("Initials") %></span><div><header><strong><%#: Eval("AuthorName") %></strong><small><%#: FormatCommentDate(Eval("CreatedAtUtc")) %></small><em runat="server" visible='<%# Convert.ToBoolean(Eval("IsInternal")) %>'>Internal note</em></header><p><%#: Eval("Body") %></p></div></article></ItemTemplate></asp:Repeater><asp:Panel ID="NoCommentsPanel" runat="server" CssClass="no-comments" Visible="false">No comments yet. Start the conversation below.</asp:Panel></div><div class="comment-composer"><asp:TextBox ID="CommentInput" runat="server" TextMode="MultiLine" Rows="4" MaxLength="4000" placeholder="Write an update or ask a question" /><div><asp:CheckBox ID="InternalInput" runat="server" Text=" Internal note (IT team only)" /><asp:Button ID="CommentButton" runat="server" Text="Post comment" CssClass="button button-primary" CausesValidation="false" /></div></div></section></div>
            <aside class="details-sidebar"><section class="panel detail-card"><div class="panel-heading"><div><h2>Ticket information</h2></div></div><dl><div><dt>Status</dt><dd><asp:Label ID="StatusBadge" runat="server" /></dd></div><div><dt>Category</dt><dd><asp:Literal ID="CategoryName" runat="server" /></dd></div><div><dt>Related asset</dt><dd><asp:Literal ID="AssetLabel" runat="server" /></dd></div><div><dt>Assigned to</dt><dd><asp:Literal ID="AssignedToName" runat="server" /></dd></div></dl></section><asp:Panel ID="WorkflowPanel" runat="server" CssClass="panel workflow-panel"><div class="panel-heading"><div><h2>Service workflow</h2><p>Assignment and state</p></div></div><div class="workflow-body"><div class="field"><label for="TechnicianInput">Assigned technician</label><asp:DropDownList ID="TechnicianInput" runat="server" /></div><asp:Button ID="AssignButton" runat="server" Text="Assign technician" CssClass="button button-secondary" CausesValidation="false" /><div class="field"><label for="StatusInput">Ticket status</label><asp:DropDownList ID="StatusInput" runat="server"><asp:ListItem>Open</asp:ListItem><asp:ListItem>Assigned</asp:ListItem><asp:ListItem Value="InProgress">In progress</asp:ListItem><asp:ListItem>Waiting</asp:ListItem><asp:ListItem>Resolved</asp:ListItem><asp:ListItem>Closed</asp:ListItem><asp:ListItem>Cancelled</asp:ListItem></asp:DropDownList></div><asp:Button ID="StatusButton" runat="server" Text="Update status" CssClass="button button-primary" CausesValidation="false" /></div></asp:Panel><section class="panel requester-card"><span class="avatar"><asp:Literal ID="RequesterInitials" runat="server" /></span><div><small>Requested by</small><strong><asp:Literal ID="RequesterName" runat="server" /></strong><span><asp:Literal ID="RequesterEmail" runat="server" /></span></div></section></aside>
        </div>
    </asp:Panel>
</asp:Content>
