<%@ Page Title="Ticket details" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="false" CodeBehind="Details.aspx.vb" Inherits="ITSupportAssetManagement.Web.TicketDetailsPage" %>
<asp:Content ID="TicketDetailsContent" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Panel ID="NotFoundPanel" runat="server" CssClass="panel empty-state" Visible="false"><span><i class="bi bi-search"></i></span><h2>Ticket not found</h2><p>The requested ticket does not exist or is no longer available.</p><a class="button button-primary" href="List.aspx">Return to tickets</a></asp:Panel>
    <asp:Panel ID="DetailsPanel" runat="server" Visible="false">
        <div class="page-heading ticket-page-heading"><div><a class="back-link" href="List.aspx"><i class="bi bi-arrow-left"></i> Back to tickets</a><div class="details-title-row"><h1><asp:Literal ID="TicketTitle" runat="server" /></h1><asp:Label ID="PriorityBadge" runat="server" /></div><p><asp:Literal ID="TicketNumber" runat="server" /> &middot; Created <asp:Literal ID="CreatedDate" runat="server" /></p></div><button class="button button-primary" type="button"><i class="bi bi-person-check"></i> Assign ticket</button></div>
        <div class="ticket-details-grid"><section class="panel details-main"><div class="panel-heading"><div><h2>Issue description</h2><p>Information provided by the requester</p></div></div><div class="description-copy"><asp:Literal ID="DescriptionText" runat="server" /></div><div class="detail-placeholder"><i class="bi bi-chat-left-text"></i><div><strong>Conversation will appear here</strong><span>Ticket comments and internal notes are coming in the next iteration.</span></div></div></section>
            <aside class="details-sidebar"><section class="panel detail-card"><div class="panel-heading"><div><h2>Ticket information</h2></div></div><dl><div><dt>Status</dt><dd><asp:Label ID="StatusBadge" runat="server" /></dd></div><div><dt>Category</dt><dd><asp:Literal ID="CategoryName" runat="server" /></dd></div><div><dt>Related asset</dt><dd><asp:Literal ID="AssetLabel" runat="server" /></dd></div><div><dt>Assigned to</dt><dd><asp:Literal ID="AssignedToName" runat="server" /></dd></div></dl></section><section class="panel requester-card"><span class="avatar"><asp:Literal ID="RequesterInitials" runat="server" /></span><div><small>Requested by</small><strong><asp:Literal ID="RequesterName" runat="server" /></strong><span><asp:Literal ID="RequesterEmail" runat="server" /></span></div></section></aside>
        </div>
    </asp:Panel>
</asp:Content>
