<%@ Page Title="Register asset" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="false" CodeBehind="Create.aspx.vb" Inherits="ITSupportAssetManagement.Web.AssetCreatePage" %>
<asp:Content ID="AssetCreateContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="page-heading ticket-page-heading"><div><a class="back-link" href="List.aspx"><i class="bi bi-arrow-left"></i> Back to inventory</a><h1>Register an asset</h1><p>Create a complete, traceable equipment record.</p></div></div>
    <asp:Panel ID="ErrorPanel" runat="server" CssClass="page-alert error" Visible="false"><i class="bi bi-exclamation-circle"></i><asp:Literal ID="ErrorMessage" runat="server" /></asp:Panel>
    <div class="asset-form-layout"><section class="panel form-panel"><div class="form-section"><div class="section-number">1</div><div class="section-copy"><h2>Asset identity</h2><p>Core identification and classification.</p></div></div><div class="form-body"><div class="form-row"><div class="field"><label for="AssetTagInput">Asset tag <em>Required</em></label><asp:TextBox ID="AssetTagInput" runat="server" MaxLength="40" placeholder="LT-0001" /><asp:RequiredFieldValidator ID="AssetTagRequired" runat="server" ControlToValidate="AssetTagInput" ErrorMessage="Asset tag is required." CssClass="field-error" Display="Dynamic" /></div><div class="field"><label for="CategoryInput">Category <em>Required</em></label><asp:DropDownList ID="CategoryInput" runat="server" /><asp:RequiredFieldValidator ID="CategoryRequired" runat="server" ControlToValidate="CategoryInput" InitialValue="" ErrorMessage="Select a category." CssClass="field-error" Display="Dynamic" /></div></div><div class="form-row"><div class="field"><label for="ManufacturerInput">Manufacturer</label><asp:TextBox ID="ManufacturerInput" runat="server" MaxLength="80" placeholder="Dell" /></div><div class="field"><label for="ModelInput">Model <em>Required</em></label><asp:TextBox ID="ModelInput" runat="server" MaxLength="120" placeholder="Latitude 5440" /><asp:RequiredFieldValidator ID="ModelRequired" runat="server" ControlToValidate="ModelInput" ErrorMessage="Model is required." CssClass="field-error" Display="Dynamic" /></div></div><div class="field"><label for="SerialNumberInput">Serial number</label><asp:TextBox ID="SerialNumberInput" runat="server" MaxLength="100" placeholder="Manufacturer serial number" /></div></div></section>
        <section class="panel form-panel"><div class="form-section"><div class="section-number">2</div><div class="section-copy"><h2>Purchase and warranty</h2><p>Financial and lifecycle information.</p></div></div><div class="form-body"><div class="form-row three"><div class="field"><label for="PurchaseDateInput">Purchase date</label><asp:TextBox ID="PurchaseDateInput" runat="server" TextMode="Date" /></div><div class="field"><label for="PurchaseCostInput">Purchase cost</label><asp:TextBox ID="PurchaseCostInput" runat="server" TextMode="Number" step="0.01" min="0" placeholder="0.00" /></div><div class="field"><label for="WarrantyEndInput">Warranty ends</label><asp:TextBox ID="WarrantyEndInput" runat="server" TextMode="Date" /></div></div></div></section>
        <section class="panel form-panel"><div class="form-section"><div class="section-number">3</div><div class="section-copy"><h2>Placement and status</h2><p>Current operational information.</p></div></div><div class="form-body"><div class="form-row"><div class="field"><label for="LocationInput">Location</label><asp:TextBox ID="LocationInput" runat="server" MaxLength="150" placeholder="Building A · Floor 2" /></div><div class="field"><label for="StatusInput">Initial status</label><asp:DropDownList ID="StatusInput" runat="server"><asp:ListItem>Available</asp:ListItem><asp:ListItem Value="InMaintenance">In maintenance</asp:ListItem><asp:ListItem>Retired</asp:ListItem></asp:DropDownList></div></div><div class="field"><label for="NotesInput">Notes</label><asp:TextBox ID="NotesInput" runat="server" TextMode="MultiLine" Rows="4" MaxLength="1000" placeholder="Accessories, condition, or other useful details" /></div></div></section>
        <div class="form-actions wide"><a class="button button-secondary" href="List.aspx">Cancel</a><asp:Button ID="CreateButton" runat="server" Text="Register asset" CssClass="button button-primary" /></div>
    </div>
</asp:Content>

