<%@ Page Title="Asset details" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="false" CodeBehind="Details.aspx.vb" Inherits="ITSupportAssetManagement.Web.AssetDetailsPage" %>
<asp:Content ID="AssetDetailsContent" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Panel ID="NotFoundPanel" runat="server" CssClass="panel empty-state" Visible="false"><span><i class="bi bi-search"></i></span><h2>Asset not found</h2><p>The requested equipment record does not exist.</p><a class="button button-primary" href="List.aspx">Return to inventory</a></asp:Panel>
    <asp:Panel ID="DetailsPanel" runat="server" Visible="false">
        <asp:Panel ID="SuccessPanel" runat="server" CssClass="page-alert success" Visible="false"><i class="bi bi-check-circle"></i><span>The asset was registered successfully.</span></asp:Panel>
        <div class="page-heading ticket-page-heading"><div><a class="back-link" href="List.aspx"><i class="bi bi-arrow-left"></i> Back to inventory</a><div class="details-title-row"><h1><asp:Literal ID="AssetName" runat="server" /></h1><asp:Label ID="StatusBadge" runat="server" /></div><p><asp:Literal ID="AssetTag" runat="server" /> · <asp:Literal ID="CategoryName" runat="server" /></p></div><div class="heading-actions"><button class="button button-secondary" type="button"><i class="bi bi-pencil"></i> Edit</button><button class="button button-primary" type="button"><i class="bi bi-person-plus"></i> Assign asset</button></div></div>
        <div class="asset-details-layout"><section class="panel asset-profile"><div class="asset-hero"><span><i class="bi bi-pc-display-horizontal"></i></span><div><small>Asset tag</small><strong><asp:Literal ID="HeroAssetTag" runat="server" /></strong></div></div><div class="asset-spec-grid"><div><span>Serial number</span><strong><asp:Literal ID="SerialNumber" runat="server" /></strong></div><div><span>Location</span><strong><asp:Literal ID="Location" runat="server" /></strong></div><div><span>Purchase date</span><strong><asp:Literal ID="PurchaseDate" runat="server" /></strong></div><div><span>Purchase cost</span><strong><asp:Literal ID="PurchaseCost" runat="server" /></strong></div><div><span>Warranty ends</span><strong><asp:Literal ID="WarrantyEnd" runat="server" /></strong></div><div><span>Registered</span><strong><asp:Literal ID="CreatedDate" runat="server" /></strong></div></div><div class="asset-notes"><h2>Notes</h2><p><asp:Literal ID="Notes" runat="server" /></p></div></section>
            <aside class="details-sidebar"><section class="panel assignment-card"><div class="panel-heading"><div><h2>Current assignment</h2><p>Equipment custody</p></div></div><asp:Panel ID="AssignedPanel" runat="server" CssClass="assigned-person" Visible="false"><span class="avatar"><asp:Literal ID="AssignedInitials" runat="server" /></span><div><small>Assigned to</small><strong><asp:Literal ID="AssignedName" runat="server" /></strong><em>Since <asp:Literal ID="AssignedDate" runat="server" /></em></div></asp:Panel><asp:Panel ID="UnassignedPanel" runat="server" CssClass="unassigned-state" Visible="false"><i class="bi bi-person-dash"></i><strong>Not assigned</strong><span>This asset is available for assignment.</span></asp:Panel></section><section class="panel lifecycle-card"><div class="panel-heading"><div><h2>Lifecycle</h2><p>Operational shortcuts</p></div></div><a href="../Tickets/Create.aspx"><span><i class="bi bi-inbox"></i> Create related ticket</span><i class="bi bi-chevron-right"></i></a><button type="button"><span><i class="bi bi-tools"></i> Schedule maintenance</span><i class="bi bi-chevron-right"></i></button><button type="button"><span><i class="bi bi-clock-history"></i> View complete history</span><i class="bi bi-chevron-right"></i></button></section></aside>
        </div>
    </asp:Panel>
</asp:Content>

