<%@ Page Title="Asset details" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="false" CodeBehind="Details.aspx.vb" Inherits="ITSupportAssetManagement.Web.AssetDetailsPage" %>
<asp:Content ID="AssetDetailsContent" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Panel ID="NotFoundPanel" runat="server" CssClass="panel empty-state" Visible="false"><span><i class="bi bi-search"></i></span><h2>Asset not found</h2><p>The requested equipment record does not exist.</p><a class="button button-primary" href="List.aspx">Return to inventory</a></asp:Panel>
    <asp:Panel ID="DetailsPanel" runat="server" Visible="false">
        <asp:Panel ID="SuccessPanel" runat="server" CssClass="page-alert success" Visible="false"><i class="bi bi-check-circle"></i><span><asp:Literal ID="SuccessMessage" runat="server" /></span></asp:Panel>
        <asp:Panel ID="ErrorPanel" runat="server" CssClass="page-alert error" Visible="false"><i class="bi bi-exclamation-circle"></i><asp:Literal ID="ErrorMessage" runat="server" /></asp:Panel>
        <div class="page-heading ticket-page-heading"><div><a class="back-link" href="List.aspx"><i class="bi bi-arrow-left"></i> Back to inventory</a><div class="details-title-row"><h1><asp:Literal ID="AssetName" runat="server" /></h1><asp:Label ID="StatusBadge" runat="server" /></div><p><asp:Literal ID="AssetTag" runat="server" /> &middot; <asp:Literal ID="CategoryName" runat="server" /></p></div><div class="heading-actions"><asp:HyperLink ID="EditLink" runat="server" CssClass="button button-secondary" Visible="false"><i class="bi bi-pencil"></i> Edit</asp:HyperLink><asp:HyperLink ID="AssignLink" runat="server" CssClass="button button-primary" Visible="false"><i class="bi bi-person-plus"></i> Assign asset</asp:HyperLink><asp:Button ID="ReturnButton" runat="server" Text="Return asset" CssClass="button button-secondary" Visible="false" OnClientClick="return confirm('Confirm that this equipment has been physically returned?');" /></div></div>
        <div class="asset-details-layout"><section class="panel asset-profile"><div class="asset-hero"><span><i class="bi bi-pc-display-horizontal"></i></span><div><small>Asset tag</small><strong><asp:Literal ID="HeroAssetTag" runat="server" /></strong></div></div><div class="asset-spec-grid"><div><span>Serial number</span><strong><asp:Literal ID="SerialNumber" runat="server" /></strong></div><div><span>Location</span><strong><asp:Literal ID="Location" runat="server" /></strong></div><div><span>Purchase date</span><strong><asp:Literal ID="PurchaseDate" runat="server" /></strong></div><div><span>Purchase cost</span><strong><asp:Literal ID="PurchaseCost" runat="server" /></strong></div><div><span>Warranty ends</span><strong><asp:Literal ID="WarrantyEnd" runat="server" /></strong></div><div><span>Registered</span><strong><asp:Literal ID="CreatedDate" runat="server" /></strong></div></div><div class="asset-notes"><h2>Notes</h2><p><asp:Literal ID="Notes" runat="server" /></p></div></section>
            <aside class="details-sidebar"><section class="panel assignment-card"><div class="panel-heading"><div><h2>Current assignment</h2><p>Equipment custody</p></div></div><asp:Panel ID="AssignedPanel" runat="server" CssClass="assigned-person" Visible="false"><span class="avatar"><asp:Literal ID="AssignedInitials" runat="server" /></span><div><small>Assigned to</small><strong><asp:Literal ID="AssignedName" runat="server" /></strong><em>Since <asp:Literal ID="AssignedDate" runat="server" /></em></div></asp:Panel><asp:Panel ID="UnassignedPanel" runat="server" CssClass="unassigned-state" Visible="false"><i class="bi bi-person-dash"></i><strong>Not assigned</strong><span>This asset is available for assignment.</span></asp:Panel></section><section class="panel lifecycle-card"><div class="panel-heading"><div><h2>Lifecycle</h2><p>Operational shortcuts</p></div></div><a href="../Tickets/Create.aspx"><span><i class="bi bi-inbox"></i> Create related ticket</span><i class="bi bi-chevron-right"></i></a><asp:HyperLink ID="ScheduleMaintenanceLink" runat="server"><span><i class="bi bi-tools"></i> Schedule maintenance</span><i class="bi bi-chevron-right"></i></asp:HyperLink><a href="#maintenance-history"><span><i class="bi bi-clock-history"></i> View complete history</span><i class="bi bi-chevron-right"></i></a></section></aside>
        </div>
        <section class="panel history-panel"><div class="panel-heading"><div><h2>Assignment history</h2><p>Complete chain of equipment custody</p></div></div><div class="history-list"><asp:Repeater ID="HistoryRepeater" runat="server"><ItemTemplate><article><span class="history-line-dot"></span><div class="history-copy"><strong><%#: Eval("UserName") %></strong><p>Assigned by <%#: Eval("AssignedByName") %> on <%#: CType(Eval("AssignedAtUtc"), DateTime).ToLocalTime().ToString("dd MMM yyyy") %></p><small><%#: DisplayHistoryNotes(Eval("AssignmentNotes")) %></small></div><span class='<%# If(Convert.ToString(Eval("StatusLabel")) = "Active", "history-status active", "history-status") %>'><%#: Eval("StatusLabel") %></span></article></ItemTemplate></asp:Repeater><asp:Panel ID="NoHistoryPanel" runat="server" CssClass="no-history" Visible="false">No assignment has been recorded for this asset.</asp:Panel></div></section>
        <section id="maintenance-history" class="panel history-panel maintenance-history-panel"><div class="panel-heading"><div><h2>Maintenance history</h2><p>Every intervention recorded for this equipment</p></div><asp:HyperLink ID="MaintenanceListLink" runat="server" CssClass="panel-link">Open maintenance <i class="bi bi-arrow-right"></i></asp:HyperLink></div><div class="maintenance-history-list"><asp:Repeater ID="MaintenanceRepeater" runat="server"><ItemTemplate><a class="maintenance-history-row" href='<%# ResolveUrl("~/Maintenance/Details.aspx?id=" & Convert.ToString(Eval("MaintenanceInterventionId"))) %>'><span class="maintenance-history-icon"><i class="bi bi-tools"></i></span><div><strong><%#: Eval("InterventionType") %> intervention</strong><small><%#: DisplayMaintenanceMeta(Eval("TechnicianName"), Eval("ScheduledAtUtc")) %></small></div><span class='<%# Eval("StatusCssClass") %>'><%#: Eval("DisplayStatus") %></span><i class="bi bi-chevron-right"></i></a></ItemTemplate></asp:Repeater><asp:Panel ID="NoMaintenancePanel" runat="server" CssClass="no-history" Visible="false">No maintenance intervention has been recorded for this asset.</asp:Panel></div></section>
    </asp:Panel>
</asp:Content>
