'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------
Partial Public Class AssetLabelPage
    Protected WithEvents NotFoundPanel As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents LabelPanel As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents AssetDetailsLink As Global.System.Web.UI.HtmlControls.HtmlAnchor
    Protected WithEvents QrImage As Global.System.Web.UI.HtmlControls.HtmlImage
    Protected WithEvents AssetTag As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents AssetName As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents Location As Global.System.Web.UI.WebControls.Literal
End Class
