<%@ Page Title="Reports" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="false" CodeBehind="Overview.aspx.vb" Inherits="ITSupportAssetManagement.Web.ReportsOverviewPage" %>
<asp:Content ID="ReportsContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="page-heading ticket-page-heading"><div><p class="eyebrow">Operational intelligence</p><h1>Performance reports</h1><p>Live service, equipment, and maintenance indicators for the Siliana site.</p></div><asp:Button ID="ExportButton" runat="server" Text="Export CSV report" CssClass="button button-primary" CausesValidation="false" /></div>
    <asp:Panel ID="ErrorPanel" runat="server" CssClass="page-alert error" Visible="false"><i class="bi bi-exclamation-circle"></i><asp:Literal ID="ErrorMessage" runat="server" /></asp:Panel>
    <section class="report-kpis"><article><span class="report-icon blue"><i class="bi bi-inbox"></i></span><div><small>Total tickets</small><strong><asp:Literal ID="TotalTicketsText" runat="server" /></strong><em><asp:Literal ID="OpenTicketsText" runat="server" /> currently open</em></div></article><article><span class="report-icon green"><i class="bi bi-check2-circle"></i></span><div><small>Resolution rate</small><strong><asp:Literal ID="ResolutionRateText" runat="server" />%</strong><em><asp:Literal ID="ResolvedTicketsText" runat="server" /> resolved tickets</em></div></article><article><span class="report-icon violet"><i class="bi bi-pc-display"></i></span><div><small>Asset inventory</small><strong><asp:Literal ID="TotalAssetsText" runat="server" /></strong><em>Registered equipment</em></div></article><article><span class="report-icon orange"><i class="bi bi-tools"></i></span><div><small>Active maintenance</small><strong><asp:Literal ID="ActiveMaintenanceText" runat="server" /></strong><em><asp:Literal ID="MaintenanceCostText" runat="server" /> TND total labor</em></div></article></section>
    <div class="report-grid"><section class="panel report-panel"><div class="panel-heading"><div><h2>Ticket status distribution</h2><p>Current service desk workload</p></div></div><div class="report-bars"><asp:Repeater ID="TicketMetricsRepeater" runat="server"><ItemTemplate><div class="report-bar-row"><div><span><%#: Eval("Label") %></span><strong><%#: Eval("Value") %></strong></div><div class="bar-track"><i style='<%# Eval("BarStyle") %>'></i></div><small><%#: Eval("Percentage", "{0:0.#}") %>%</small></div></ItemTemplate></asp:Repeater><asp:Panel ID="NoTicketData" runat="server" CssClass="report-empty" Visible="false">No ticket data yet.</asp:Panel></div></section>
        <section class="panel report-panel"><div class="panel-heading"><div><h2>Asset fleet distribution</h2><p>Equipment lifecycle condition</p></div></div><div class="report-bars asset-bars"><asp:Repeater ID="AssetMetricsRepeater" runat="server"><ItemTemplate><div class="report-bar-row"><div><span><%#: Eval("Label") %></span><strong><%#: Eval("Value") %></strong></div><div class="bar-track"><i style='<%# Eval("BarStyle") %>'></i></div><small><%#: Eval("Percentage", "{0:0.#}") %>%</small></div></ItemTemplate></asp:Repeater><asp:Panel ID="NoAssetData" runat="server" CssClass="report-empty" Visible="false">No asset data yet.</asp:Panel></div></section>
        <section class="panel report-panel report-wide"><div class="panel-heading"><div><h2>Maintenance portfolio</h2><p>Interventions grouped by technical purpose</p></div></div><div class="maintenance-report-grid"><asp:Repeater ID="MaintenanceMetricsRepeater" runat="server"><ItemTemplate><article><span><i class="bi bi-wrench-adjustable"></i></span><div><small><%#: Eval("Label") %></small><strong><%#: Eval("Value") %></strong><em><%#: Eval("Percentage", "{0:0.#}") %>% of interventions</em></div></article></ItemTemplate></asp:Repeater><asp:Panel ID="NoMaintenanceData" runat="server" CssClass="report-empty" Visible="false">No maintenance data yet.</asp:Panel></div></section>
    </div>
</asp:Content>
