<%@ Page Title="Maintenance calendar" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="false" CodeBehind="Calendar.aspx.vb" Inherits="ITSupportAssetManagement.Web.MaintenanceCalendarPage" %>
<asp:Content ID="CalendarContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="page-heading ticket-page-heading"><div><p class="eyebrow"><i class="bi bi-calendar3"></i> Maintenance operations</p><h1>Maintenance calendar</h1><p>See planned work, active repairs, and overdue interventions by date.</p></div><div class="heading-actions"><a class="button button-secondary" href="List.aspx"><i class="bi bi-list-ul"></i> List view</a><asp:PlaceHolder ID="PlanAction" runat="server"><a class="button button-primary" href="Create.aspx"><i class="bi bi-plus-lg"></i> Plan intervention</a></asp:PlaceHolder></div></div>
    <asp:Panel ID="ErrorPanel" runat="server" CssClass="page-alert error" Visible="false"><i class="bi bi-exclamation-circle"></i><asp:Literal ID="ErrorMessage" runat="server" /></asp:Panel>
    <section class="panel maintenance-calendar">
        <header class="calendar-toolbar"><a id="PreviousMonthLink" runat="server" class="calendar-nav" aria-label="Previous month"><i class="bi bi-chevron-left"></i></a><div><small>Schedule</small><h2><asp:Literal ID="MonthTitle" runat="server" /></h2></div><a id="NextMonthLink" runat="server" class="calendar-nav" aria-label="Next month"><i class="bi bi-chevron-right"></i></a></header>
        <div class="calendar-legend"><span><i class="planned"></i> Planned</span><span><i class="progress"></i> In progress</span><span><i class="completed"></i> Completed</span><span><i class="overdue"></i> Overdue</span></div>
        <div class="calendar-weekdays"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div>
        <div class="calendar-grid"><asp:Repeater ID="DayRepeater" runat="server"><ItemTemplate><article class='<%# Eval("CssClass") %>'><header><span><%# DirectCast(Eval("Date"), DateTime).Day %></span><em><%# If(Convert.ToBoolean(Eval("IsToday")), "Today", String.Empty) %></em></header><div class="calendar-events"><asp:Repeater ID="EventRepeater" runat="server" DataSource='<%# Eval("Items") %>'><ItemTemplate><a class='<%# EventClass(Container.DataItem) %>' href='<%# "Details.aspx?id=" & Convert.ToString(Eval("MaintenanceInterventionId")) %>' title='<%# Server.HtmlEncode(Convert.ToString(Eval("AssetName"))) %>'><span><%#: DisplayEventTime(Eval("ScheduledAtUtc")) %></span><strong><%#: Eval("AssetTag") %></strong><small><%#: Eval("InterventionType") %></small></a></ItemTemplate></asp:Repeater></div></article></ItemTemplate></asp:Repeater></div>
        <footer class="calendar-footer"><span><asp:Literal ID="ScheduledCount" runat="server" /> scheduled interventions</span><small>Times shown in local Siliana time</small></footer>
    </section>
</asp:Content>
