<%@ Page Title="Plan maintenance" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="false" CodeBehind="Create.aspx.vb" Inherits="ITSupportAssetManagement.Web.MaintenanceCreatePage" %>
<asp:Content ID="MaintenanceCreateContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="page-heading ticket-page-heading"><div><a class="back-link" href="List.aspx"><i class="bi bi-arrow-left"></i> Back to maintenance</a><h1>Plan an intervention</h1><p>Schedule technical work and assign clear ownership.</p></div></div>
    <asp:Panel ID="ErrorPanel" runat="server" CssClass="page-alert error" Visible="false"><i class="bi bi-exclamation-circle"></i><asp:Literal ID="ErrorMessage" runat="server" /></asp:Panel>
    <div class="ticket-form-grid"><section class="panel form-panel"><div class="form-section"><div class="section-number">1</div><div class="section-copy"><h2>Intervention details</h2><p>Select the equipment, work type, and technician.</p></div></div><div class="form-body">
        <div class="form-row"><div class="field"><label for="AssetInput">Asset <em>Required</em></label><asp:DropDownList ID="AssetInput" runat="server" /><asp:RequiredFieldValidator ID="AssetRequired" runat="server" ControlToValidate="AssetInput" InitialValue="" ErrorMessage="Select an asset." CssClass="field-error" Display="Dynamic" /></div><div class="field"><label for="TypeInput">Intervention type <em>Required</em></label><asp:DropDownList ID="TypeInput" runat="server"><asp:ListItem Value="">Select a type</asp:ListItem><asp:ListItem>Preventive</asp:ListItem><asp:ListItem>Corrective</asp:ListItem><asp:ListItem>Inspection</asp:ListItem><asp:ListItem>Upgrade</asp:ListItem></asp:DropDownList><asp:RequiredFieldValidator ID="TypeRequired" runat="server" ControlToValidate="TypeInput" InitialValue="" ErrorMessage="Select an intervention type." CssClass="field-error" Display="Dynamic" /></div></div>
        <div class="form-row"><div class="field"><label for="TechnicianInput">Technician</label><asp:DropDownList ID="TechnicianInput" runat="server" /></div><div class="field"><label for="ScheduledInput">Scheduled date and time</label><asp:TextBox ID="ScheduledInput" runat="server" TextMode="DateTimeLocal" /></div></div>
        <div class="field"><label for="ProviderInput">External provider</label><asp:TextBox ID="ProviderInput" runat="server" MaxLength="150" placeholder="Optional supplier or service provider" /></div>
        <div class="field"><label for="DiagnosisInput">Initial diagnosis or scope</label><asp:TextBox ID="DiagnosisInput" runat="server" TextMode="MultiLine" Rows="6" placeholder="Describe the issue, inspection scope, or preventive work to perform" /></div>
    </div></section><aside class="form-sidebar"><section class="assignment-guidance"><span class="guidance-icon"><i class="bi bi-shield-check"></i></span><h2>Controlled maintenance</h2><p>The platform keeps the equipment status synchronized throughout the intervention.</p><ul><li>Plan without interrupting availability</li><li>Start work when the asset is received</li><li>Record diagnosis, actions, and cost</li></ul></section><div class="form-actions"><a class="button button-secondary" href="List.aspx">Cancel</a><asp:Button ID="CreateButton" runat="server" Text="Plan intervention" CssClass="button button-primary" /></div></aside></div>
</asp:Content>
