<%@ Page Title="Maintenance details" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="false" CodeBehind="Details.aspx.vb" Inherits="ITSupportAssetManagement.Web.MaintenanceDetailsPage" %>
<asp:Content ID="MaintenanceDetailsContent" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Panel ID="NotFoundPanel" runat="server" CssClass="empty-state panel" Visible="false"><span><i class="bi bi-exclamation-triangle"></i></span><h2>Intervention not found</h2><p>The record may have been removed or the link is invalid.</p><a class="button button-primary" href="List.aspx">Back to maintenance</a></asp:Panel>
    <asp:Panel ID="DetailsPanel" runat="server" Visible="false">
        <div class="page-heading ticket-page-heading"><div><a class="back-link" href="List.aspx"><i class="bi bi-arrow-left"></i> Back to maintenance</a><div class="details-title-row"><h1>#MNT-<asp:Literal ID="InterventionNumber" runat="server" /></h1><asp:Label ID="StatusBadge" runat="server" /></div><p><asp:Literal ID="InterventionType" runat="server" /> intervention for <asp:Literal ID="HeadingAsset" runat="server" /></p></div><asp:HyperLink ID="EditLink" runat="server" CssClass="button button-secondary" Visible="false"><i class="bi bi-pencil"></i> Edit intervention</asp:HyperLink></div>
        <asp:Panel ID="SuccessPanel" runat="server" CssClass="page-alert success" Visible="false"><i class="bi bi-check-circle"></i><asp:Literal ID="SuccessMessage" runat="server" /></asp:Panel>
        <asp:Panel ID="ErrorPanel" runat="server" CssClass="page-alert error" Visible="false"><i class="bi bi-exclamation-circle"></i><asp:Literal ID="ErrorMessage" runat="server" /></asp:Panel>
        <div class="maintenance-details-grid"><div class="maintenance-main">
            <section class="panel maintenance-asset-hero"><span><i class="bi bi-pc-display-horizontal"></i></span><div><small>Equipment under service</small><strong><asp:Literal ID="AssetName" runat="server" /></strong><a id="AssetLink" runat="server"><asp:Literal ID="AssetTag" runat="server" /> <i class="bi bi-arrow-up-right"></i></a></div><div class="maintenance-location"><small>Location</small><strong><asp:Literal ID="AssetLocation" runat="server" /></strong></div></section>
            <section class="panel maintenance-copy-card"><div class="panel-heading"><div><h2>Diagnosis and scope</h2><p>Technical assessment</p></div></div><p><asp:Literal ID="Diagnosis" runat="server" /></p></section>
            <section class="panel maintenance-copy-card"><div class="panel-heading"><div><h2>Work performed</h2><p>Completed service record</p></div></div><p><asp:Literal ID="WorkPerformed" runat="server" /></p></section>
            <section class="panel parts-card"><div class="panel-heading"><div><h2>Parts and materials</h2><p>Items consumed during this intervention</p></div><strong class="parts-total"><asp:Literal ID="PartsTotal" runat="server" /></strong></div><div class="parts-list"><asp:Repeater ID="PartsRepeater" runat="server"><ItemTemplate><article><span><i class="bi bi-box-seam"></i></span><div><strong><%#: Eval("PartName") %></strong><small><%#: DisplayPartNumber(Eval("PartNumber")) %></small></div><em><%#: Eval("Quantity") %> × <%#: DisplayMoney(Eval("UnitCost")) %></em><b><%#: DisplayMoney(Eval("LineTotal")) %></b></article></ItemTemplate></asp:Repeater><asp:Panel ID="NoPartsPanel" runat="server" CssClass="no-history" Visible="false">No parts or materials have been recorded.</asp:Panel></div><asp:Panel ID="AddPartPanel" runat="server" CssClass="part-composer" Visible="false"><div class="field"><label for="PartNameInput">Part or material</label><asp:TextBox ID="PartNameInput" runat="server" MaxLength="150" placeholder="Example: SSD 1 TB" /></div><div class="part-form-row"><div class="field"><label for="PartNumberInput">Part number</label><asp:TextBox ID="PartNumberInput" runat="server" MaxLength="100" placeholder="Optional" /></div><div class="field"><label for="QuantityInput">Quantity</label><asp:TextBox ID="QuantityInput" runat="server" TextMode="Number" Text="1" min="1" /></div><div class="field"><label for="UnitCostInput">Unit cost (TND)</label><asp:TextBox ID="UnitCostInput" runat="server" TextMode="Number" min="0" step="0.01" /></div></div><asp:Button ID="AddPartButton" runat="server" Text="Add part" CssClass="button button-secondary" CausesValidation="false" /></asp:Panel></section>
            <asp:Panel ID="CompletionPanel" runat="server" CssClass="panel completion-panel" Visible="false"><div class="form-section"><div class="section-number"><i class="bi bi-check2"></i></div><div class="section-copy"><h2>Complete intervention</h2><p>Document the final technical outcome.</p></div></div><div class="form-body"><div class="field"><label for="DiagnosisInput">Final diagnosis</label><asp:TextBox ID="DiagnosisInput" runat="server" TextMode="MultiLine" Rows="4" /></div><div class="field"><label for="WorkInput">Work performed <em>Required</em></label><asp:TextBox ID="WorkInput" runat="server" TextMode="MultiLine" Rows="5" /><asp:RequiredFieldValidator ID="WorkRequired" runat="server" ControlToValidate="WorkInput" ErrorMessage="Describe the work performed." CssClass="field-error" Display="Dynamic" ValidationGroup="Complete" /></div><div class="field"><label for="LaborCostInput">Labor cost (TND)</label><asp:TextBox ID="LaborCostInput" runat="server" TextMode="Number" min="0" step="0.01" placeholder="0.00" /></div><asp:Button ID="CompleteButton" runat="server" Text="Complete intervention" CssClass="button button-primary" ValidationGroup="Complete" /></div></asp:Panel>
        </div><aside class="details-sidebar">
            <section class="panel detail-card"><div class="panel-heading"><div><h2>Intervention details</h2><p>Schedule and ownership</p></div></div><dl><div><dt>Type</dt><dd><asp:Literal ID="DetailType" runat="server" /></dd></div><div><dt>Technician</dt><dd><asp:Literal ID="Technician" runat="server" /></dd></div><div><dt>Scheduled</dt><dd><asp:Literal ID="Scheduled" runat="server" /></dd></div><div><dt>Started</dt><dd><asp:Literal ID="Started" runat="server" /></dd></div><div><dt>Completed</dt><dd><asp:Literal ID="Completed" runat="server" /></dd></div><div><dt>External provider</dt><dd><asp:Literal ID="Provider" runat="server" /></dd></div><div><dt>Labor cost</dt><dd><asp:Literal ID="LaborCost" runat="server" /></dd></div><div class="grand-total"><dt>Total cost</dt><dd><asp:Literal ID="TotalCost" runat="server" /></dd></div></dl></section>
            <asp:Panel ID="ActionsPanel" runat="server" CssClass="panel intervention-actions"><div class="panel-heading"><div><h2>Workflow actions</h2><p>Move the intervention forward</p></div></div><asp:Button ID="StartButton" runat="server" Text="Start intervention" CssClass="action-button start" CausesValidation="false" /><asp:Button ID="CancelButton" runat="server" Text="Cancel intervention" CssClass="action-button cancel" CausesValidation="false" /></asp:Panel>
        </aside></div>
    </asp:Panel>
</asp:Content>
