<%@ Page Title="Maintenance" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="false" CodeBehind="List.aspx.vb" Inherits="ITSupportAssetManagement.Web.MaintenanceListPage" %>
<asp:Content ID="MaintenanceListContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="page-heading ticket-page-heading"><div><p class="eyebrow">Maintenance operations</p><h1>Intervention planner</h1><p>Plan preventive work, execute repairs, and preserve a complete service history.</p></div><div class="heading-actions"><a class="button button-secondary" href="Calendar.aspx"><i class="bi bi-calendar3"></i> Calendar</a><a class="button button-primary" href="Create.aspx"><i class="bi bi-calendar2-plus"></i> Plan intervention</a></div></div>
    <asp:Panel ID="SuccessPanel" runat="server" CssClass="page-alert success" Visible="false"><i class="bi bi-check-circle"></i><span>The maintenance intervention was created successfully.</span></asp:Panel>
    <asp:Panel ID="ErrorPanel" runat="server" CssClass="page-alert error" Visible="false"><i class="bi bi-exclamation-circle"></i><asp:Literal ID="ErrorMessage" runat="server" /></asp:Panel>
    <section class="panel tickets-workspace">
        <div class="ticket-toolbar"><div class="filter-search"><i class="bi bi-search"></i><asp:TextBox ID="SearchInput" runat="server" MaxLength="150" placeholder="Search asset, tag, or technician" /></div><asp:DropDownList ID="StatusFilter" runat="server"><asp:ListItem Value="">All statuses</asp:ListItem><asp:ListItem>Planned</asp:ListItem><asp:ListItem Value="InProgress">In progress</asp:ListItem><asp:ListItem>Completed</asp:ListItem><asp:ListItem>Cancelled</asp:ListItem></asp:DropDownList><asp:DropDownList ID="TypeFilter" runat="server"><asp:ListItem Value="">All types</asp:ListItem><asp:ListItem>Preventive</asp:ListItem><asp:ListItem>Corrective</asp:ListItem><asp:ListItem>Inspection</asp:ListItem><asp:ListItem>Upgrade</asp:ListItem></asp:DropDownList><asp:Button ID="FilterButton" runat="server" Text="Apply filters" CssClass="button button-secondary" /></div>
        <div class="ticket-table-wrap"><table class="data-table maintenance-table"><thead><tr><th>Intervention</th><th>Asset</th><th>Type</th><th>Technician</th><th>Scheduled</th><th>Status</th><th></th></tr></thead><tbody><asp:Repeater ID="InterventionRepeater" runat="server"><ItemTemplate><tr>
            <td><a class="maintenance-id" href='<%# "Details.aspx?id=" & Convert.ToString(Eval("MaintenanceInterventionId")) %>'>#MNT-<%# Convert.ToInt32(Eval("MaintenanceInterventionId")).ToString("D4") %></a></td>
            <td><a class="ticket-cell" href='<%# "Details.aspx?id=" & Convert.ToString(Eval("MaintenanceInterventionId")) %>'><strong><%#: Eval("AssetName") %></strong><span><%#: Eval("AssetTag") %></span></a></td>
            <td><span class="maintenance-type"><i class="bi bi-tools"></i><%#: Eval("InterventionType") %></span></td><td><%#: DisplayOrDefault(Eval("TechnicianName"), "Unassigned") %></td>
            <td><%#: DisplaySchedule(Eval("ScheduledAtUtc")) %></td><td><span class='<%# Eval("StatusCssClass") %>'><i></i><%#: Eval("DisplayStatus") %></span></td><td><a class="row-action" href='<%# "Details.aspx?id=" & Convert.ToString(Eval("MaintenanceInterventionId")) %>'><i class="bi bi-arrow-right"></i></a></td>
        </tr></ItemTemplate></asp:Repeater></tbody></table></div>
        <asp:Panel ID="EmptyPanel" runat="server" CssClass="empty-state" Visible="false"><span><i class="bi bi-calendar2-check"></i></span><h2>No interventions found</h2><p>Change the filters or schedule the first maintenance intervention.</p><a class="button button-primary" href="Create.aspx">Plan intervention</a></asp:Panel>
        <div class="table-footer"><span><asp:Literal ID="ResultCount" runat="server" /> interventions</span><small>Active work appears first</small></div>
    </section>
</asp:Content>
