<%@ Page Title="Team" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="false" CodeBehind="List.aspx.vb" Inherits="ITSupportAssetManagement.Web.TeamListPage" %>
<asp:Content ID="TeamContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="page-heading ticket-page-heading"><div><p class="eyebrow">People and access</p><h1>IT operations team</h1><p>Manage employee identities, departments, and platform responsibilities.</p></div><asp:HyperLink ID="CreateLink" runat="server" CssClass="button button-primary" NavigateUrl="Create.aspx"><i class="bi bi-person-plus"></i> Add team member</asp:HyperLink></div>
    <asp:Panel ID="SuccessPanel" runat="server" CssClass="page-alert success" Visible="false"><i class="bi bi-check-circle"></i>The team member account was created successfully.</asp:Panel>
    <asp:Panel ID="ErrorPanel" runat="server" CssClass="page-alert error" Visible="false"><i class="bi bi-exclamation-circle"></i><asp:Literal ID="ErrorMessage" runat="server" /></asp:Panel>
    <section class="panel tickets-workspace"><div class="ticket-toolbar team-toolbar"><div class="filter-search"><i class="bi bi-search"></i><asp:TextBox ID="SearchInput" runat="server" MaxLength="150" placeholder="Search name, email, code, or department" /></div><asp:DropDownList ID="RoleFilter" runat="server"><asp:ListItem Value="">All roles</asp:ListItem><asp:ListItem>Administrator</asp:ListItem><asp:ListItem>ITManager</asp:ListItem><asp:ListItem>Technician</asp:ListItem><asp:ListItem>Employee</asp:ListItem></asp:DropDownList><asp:Button ID="FilterButton" runat="server" Text="Apply filters" CssClass="button button-secondary" /></div>
        <div class="team-grid"><asp:Repeater ID="TeamRepeater" runat="server"><ItemTemplate><article class="team-card"><div class="team-card-top"><span class="team-avatar"><%#: Eval("Initials") %></span><span class='<%# If(Convert.ToBoolean(Eval("IsActive")), "team-status active", "team-status") %>'><i></i><%#: Eval("StatusText") %></span></div><h2><%#: Eval("DisplayName") %></h2><p><%#: DisplayOrDefault(Eval("Department"), "No department") %></p><span class="role-chip"><i class="bi bi-shield-check"></i><%#: Eval("RoleName") %></span><dl><div><dt>Employee code</dt><dd><%#: DisplayOrDefault(Eval("EmployeeCode"), "Not set") %></dd></div><div><dt>Email</dt><dd><%#: Eval("Email") %></dd></div><div><dt>Phone</dt><dd><%#: DisplayOrDefault(Eval("PhoneNumber"), "Not set") %></dd></div></dl></article></ItemTemplate></asp:Repeater></div>
        <asp:Panel ID="EmptyPanel" runat="server" CssClass="empty-state" Visible="false"><span><i class="bi bi-people"></i></span><h2>No team members found</h2><p>Change the filters or create a new account.</p></asp:Panel><div class="table-footer"><span><asp:Literal ID="ResultCount" runat="server" /> team members</span><small>Active accounts appear first</small></div>
    </section>
</asp:Content>
